repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        files: \.(py)$
        args:
          [
            '--rcfile=.pylintrc',
            '-rn',
            '-sn',
            '--load-plugins=pylint.extensions.docparams',
          ]
